Unit test
thecodechaser/school-library pull request #7
Opened 2022-03-08 14:40 UTC by thecodechaser

## This branch includes the following features:
- Written unit tests for the classes: 
  - Book
  - Person
  - Student
  - Teacher
  - Classroom
  - Corrector
  - Rental

2022-03-08 15:01 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @thecodechaser and @akucintavalent,

Good job so far!
✔️ Tests are passing
✔️ Tests are wrapped in `describe` and `it` blocks
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### 🛑  Look here too 🛑 
- [ ] **In your README, kindly add instructions on how to run the tests**

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-08 15:01 UTC, TedLivist commented on spec/person_spec.rb
> +end
- [ ] I would recommend you add **negative** and **positive** case scenario tests for the `can_use_services?` method in the Person class.

- [ ] Kindly add unit tests for the `validate_name` method.

- [ ] Kindly add unit tests for the `add_rental` method in the Person class.

2022-03-08 15:01 UTC, TedLivist commented on spec/student_spec.rb
> +end
- [ ] Kindly add a test for the `play_hooky` method in the Student class.

2022-03-09 06:08 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @thecodechaser, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 06:22 UTC, merged